title: Fernando Campos
description: CV and information
theme: jekyll-theme-minimal

author:
  name: Fernando Eder Campos Gonzales
  email: fecampos1302@gmail.com

show_downloads: false

github:
  is_project_page: false


